language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - composer require --no-update jakub-onderka/php-parallel-lint
    - composer install --prefer-dist -o --no-interaction

script:
    - vendor/bin/parallel-lint src/ test/
    - phpunit --coverage-text
